# Generated by Django 3.1.7 on 2021-03-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('year', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('no_smoothing', models.FloatField()),
                ('lowess', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Co2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('monthly_average', models.FloatField()),
                ('de_season_alized', models.FloatField()),
                ('st_dev_mon', models.FloatField()),
                ('unc_of_mean', models.FloatField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_work.temperature')),
            ],
        ),
    ]
